apiVersion: apps/v1
kind: Deployment
metadata:
  name: aers-backend
  namespace: aers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aers-backend
  template:
    metadata:
      labels:
        app: aers-backend
    spec:
      containers:
      - name: backend
        image: priyobrotokarmakar/alert-escalation-resolution-system-backend:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        envFrom:
        - secretRef:
            name: aers-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: aers-backend
  namespace: aers
spec:
  type: LoadBalancer
  selector:
    app: aers-backend
  ports:
  - port: 8080
    targetPort: 8080
