apiVersion: apps/v1
kind: Deployment
metadata:
  name: aers-frontend
  namespace: aers
  labels:
    app: aers-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aers-frontend
  template:
    metadata:
      labels:
        app: aers-frontend
    spec:
      containers:
      - name: aers-frontend
        image: priyobrotokarmakar/alert-escalation-resolution-system-frontend:v5
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: aers-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: aers-frontend
  namespace: aers
spec:
  selector:
    app: aers-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
