package alerts

import (
	"context"
	"strings"
	"time"

	"aers-backend/internal/models"
	"aers-backend/internal/rules"
	"aers-backend/pkg/cache"

	"github.com/google/uuid"
	"go.mongodb.org/mongo-driver/bson"
)

type AlertService struct {
	repo   *Repository
	engine *rules.Engine
	cache  *cache.Cache
}

func NewAlertService(repo *Repository, engine *rules.Engine, cache *cache.Cache) *AlertService {
	return &AlertService{
		repo:   repo,
		engine: engine,
		cache:  cache,
	}
}

func (s *AlertService) IngestAlert(ctx context.Context, alert models.Alert) (string, error) {
	alert.AlertID = "ALT-" + uuid.New().String()[:8]
	alert.Status = models.StatusOpen
	alert.Timestamp = time.Now()

	alert.History = []models.HistoryEntry{
		{
			State: models.StatusOpen,
			Time:  alert.Timestamp,
			Note:  "Alert generated by " + alert.SourceType + " module",
		},
	}

	if s.engine.EvaluateAutoClose(&alert) {
		alert.Status = models.StatusAutoClosed

		alert.History = append(alert.History, models.HistoryEntry{
			State: models.StatusAutoClosed,
			Time:  time.Now(),
			Note:  "Auto-closed due to compliance rule",
		})
	} else {
	
		normalizedSourceType := strings.ToLower(strings.TrimSpace(alert.SourceType))
		rule, exists := s.engine.Config[normalizedSourceType]

		if exists && rule.WindowMins > 0 {
			driverID := alert.Metadata["driverId"]
			if driverID != nil {
				cutoff := time.Now().Add(-time.Duration(rule.WindowMins) * time.Minute)

				filter := bson.M{
					"sourceType":        alert.SourceType,
					"metadata.driverId": driverID,
					"timestamp":         bson.M{"$gte": cutoff},
				}

				recentCount, _ := s.repo.collection.CountDocuments(ctx, filter)
				s.engine.EvaluateEscalation(&alert, int(recentCount)+1)

				if alert.Status == models.StatusEscalated {
					alert.History = append(alert.History, models.HistoryEntry{
						State: models.StatusEscalated,
						Time:  time.Now(),
						Note:  "Auto-escalated by Rule Engine",
					})
				}
			}
		}
	}

	err := s.repo.Create(ctx, &alert)
	if err == nil {
		s.invalidateDashboardCache(ctx)
	}
	return alert.AlertID, err
}

func (s *AlertService) GetAlert(ctx context.Context, alertID string) (*models.Alert, error) {
	return s.repo.GetByID(ctx, alertID)
}

func (s *AlertService) ResolveAlert(ctx context.Context, alertID string) error {
	err := s.repo.UpdateStatus(ctx, alertID, models.StatusResolved)
	if err == nil {
		s.invalidateDashboardCache(ctx)
	}
	return err
}


func (s *AlertService) invalidateDashboardCache(ctx context.Context) {

	if s.cache == nil {
		return
	}

	keys := []string{
		"dashboard:stats",
		"dashboard:top_offenders",
		"dashboard:recent_events",
		"dashboard:trends",
	}
	for _, key := range keys {
		s.cache.Invalidate(ctx, key)
	}
}
